name: hello_angel
dependencies:
    angel_framework: ^2.0.0
    angel_model: ^1.0.0
    angel_orm: ^2.0.0-dev
    angel_migration_runner: ^2.0.0-dev
    angel_migration: ^2.0.0-dev
    angel_serialize: ^2.0.0

dev_dependencies:
  angel_orm_generator: ^2.0.0-dev
  angel_serialize_generator: ^2.0.0
  build_runner: ^1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'